# Spring Data Source ??
spring:
  datasource:
    url: jdbc:mysql://db-ld296-kr.vpc-pub-cdb.ntruss.com/studydb
    username: study
    password: Bitcamp!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
